name: "Update binaries"

on:
  schedule:
    # run at midnight
    - cron: "0 0 * * *"
  push:
    paths:
      - "data/firmwareRepositories.csv"
      - "data/read.sh"
  workflow_dispatch:

jobs:
  update-binaries:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ github.head_ref }}
      - name: Check if new release
        id: repos
        run: |
          cd data/
          ./read.sh
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Firmware update changes
